[versions]
loom = "1.11.7"
githubRelease = "2.4.1"
minotaur = "2.+"

kaleidoConfig = "0.3.1+1.3.2"

mc = "1.21.5"
fl = "0.16.10"
yarn = "1.21.5+build.1"
fapi = "0.121.0+1.21.5"

serverTranslationsApi = "2.5.1+1.21.5"

owo = "0.12.21+1.21.5"

cardinal = "6.3.1"

fabrictailor = "2.6.6"
fabrication = "3.4.9+1.20.4"
styledNicknames = "1.8.0+1.21.5"
placeholder = "2.6.4+1.21.5"
playerData = "0.7.0+1.21.5"
luaj = "3.0.8-figura"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
kaleidoConfig = { group = "folk.sisby", name = "kaleido-config", version.ref = "kaleidoConfig" }

mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }

serverTranslationsApi = { group = "xyz.nucleoid", name = "server-translations-api", version.ref = "serverTranslationsApi" }

owo = { group = "io.wispforest", name = "owo-lib", version.ref = "owo" }

cardinal = { group = "org.ladysnake.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal" }

fabrictailor = { group = "maven.modrinth", name = "fabrictailor", version.ref = "fabrictailor" }
fabrication = { group = "maven.modrinth", name = "fabrication", version.ref = "fabrication" }
styledNicknames = { group = "maven.modrinth", name = "styled-nicknames", version.ref = "styledNicknames" }
placeholder = { group = "eu.pb4", name = "placeholder-api", version.ref = "placeholder" }
playerData = { group = "eu.pb4", name = "player-data-api", version.ref = "playerData" }
luaj = { group = "com.github.FiguraMC.luaj", name = "luaj-core", version.ref = "luaj" }
